version: "3"
services:
  python:
    build: .
    volumes:
      - "./:/usr/src/app"
    ports:
      - "8000:8000"
    working_dir: /usr/src/app
    command:
      - /bin/sh
      - -c
      - |
          pip install pipenv
          pip install email-validator
          pipenv install --system
          uvicorn main:app --reload --host 0.0.0.0
